version: '3.8'

services:
  server:
    container_name: NODE_APP
    build: '.'
    depends_on:
      - db
    links:
      - db
    ports:
      - '3002:3001'
    networks:
      - host

  db:
    image: 'mongo'
    container_name: MONGODB_APP
    ports:
      - '27018:27017'
    networks:
      - host
  
networks: 
  host:
    driver: bridge